services:
 db3:
  image: mysql:latest
  environment: 
   MYSQL_ROOT_PASSWORD: root
   MYSQL_USER: user
   MYSQL_PASSWORD: root
  ports:
   - 3306:3306
  volumes:
   - multitenant:/var/lib/mysql #Just define the volume, no init scripts
volumes:
 multitenant: #empty volume declaration
